# A sample Gemfile
source "http://rubygems.org"

gem "sinatra"
gem "json", "~>1.4.0"
gem "sequel"
gem "mysql2"


group :development do 
  gem "rspec", ">= 2.0.0"
  gem "growl"
  gem "guard"
  gem "guard-rspec"
  gem "rb-fsevent"
  gem "shotgun"
  gem "dictionary"

end
