# A sample Gemfile
source "http://rubygems.org"

gem "sinatra"
gem "json", "~>1.4.0"
gem "sequel"


group :development do 
  gem "rspec", ">= 2.0.0"
  gem "growl"
  gem "guard"
  gem "guard-rspec"
  gem "rb-fsevent"
  gem "activesupport", "=2.3.8"
end
